steps:
- name: 'gcr.io/cloud-builders/npm'
  id: Install packages
  args:
   - 'install'
- name: 'gcr.io/cloud-builders/npm'
  id: Generate build
  args:
   - 'run'
   - 'build'
- name: 'gcr.io/cloud-builders/docker'
  id: Build docker image
  args:
    - 'build'
    - '--no-cache'
    - '-t'
    - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
    - './bin'
- name: 'gcr.io/cloud-builders/docker'
  id: Push docker image to cloud registry
  args:
    - 'push'
    - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  id: Deploy image to cloud run
  args:
    - run
    - services
    - update
    - $_SERVICE_NAME
    - '--platform=managed'
    - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
    - '--region=$_DEPLOY_REGION'
    - '--quiet'
  entrypoint: gcloud
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _SERVICE_NAME: trim
  _DEPLOY_REGION: asia-east1
  _GCR_HOSTNAME: gcr.io