version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DOMAIN=trimz.tk
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - DATABASE_URL=mongodb://mongodb:27017/URL-Shortener
    depends_on:
      - redis
      - mongodb
  redis:
    image: redis
    restart: always
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017