version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
    environment:
      - PORT=3000
      - DOMAIN=trimz.tk
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - DATABASE_URL=
    depends_on:
      - redis
  redis:
    image: redis